Final Revision for A1
COMP-345-Team-Project/eight-minute-empire-legends pull request #18
Opened 2021-02-18 02:55 UTC by goldenfire-yue

Working Part 4 Cards/Deck

2021-02-18 03:02 UTC, jonZlotnik requested changes
We're working in one solution. To help with separation and modularity of our code, we're working in separate projects, but should all be in the same solution so we can build the whole game in one shot and easy inter-project dependencies.

2021-02-18 03:02 UTC, jonZlotnik commented on EightMinuteEmpireLegends/Cards/Cards.sln
> +﻿
We're working in one solution. Don't create a new solution just for the cards/deck feature.

2021-02-19 02:18 UTC, jonZlotnik submitted a review, later dismissed

2021-02-20 19:00 UTC, joshpham97 approved these changes
All good! One small comment is that you are always exchanging the first card in the hand in the demo mode. Not a big deal, but if you want to improve the test you can make it random. Personally, I don't think you need to change it for the demo.

2021-02-20 20:26 UTC, merged