A2 gamestart
COMP-345-Team-Project/eight-minute-empire-legends pull request #35
Opened 2021-03-25 20:46 UTC by jaforte

2021-03-26 18:45 UTC, jonZlotnik requested changes
Good work. Just remove that file, then I think it's ready to merge.

2021-03-26 18:45 UTC, jonZlotnik commented on EightMinuteEmpireLegends/Core/GameBuilderException.h
> +class GameBuilderException : public std::exception
I think you meant to delete this file. Seems to be a duplicate of the one in Core/GameCore dir

2021-03-26 20:25 UTC, joshpham97 requested changes

2021-03-26 20:25 UTC, joshpham97 commented on EightMinuteEmpireLegends/Core/GameCore/GameCore.cpp
> +Game* GameBuilder::build(int numPlayers, Map& map, std::string path) {
As discussed, the logic to load the map should be in the build method because it is part of the creation logic.  We also need to let the players select their player names. The options I proposed to Jason is to pass the map path as a string (instead of a map object) to the builder and a list of player names to the build() method. 

The player input can either be handled in the main game (so we have separation of user input and game creation), or we can over load the build() method with (1) a build method that excepts no params and let player selects map, player names and (2) a build method with params that builds the game object. (1) will call (2) once user input is completed.

2021-03-27 01:44 UTC, jaforte commented on EightMinuteEmpireLegends/Core/GameCore/GameCore.cpp
> +Game* GameBuilder::build(int numPlayers, Map& map, std::string path) {
Just as a reminder to myself, I'd also like to add an operator overload for << in Game which will call the << function for all its members. Will be useful for debugging

2021-03-27 20:22 UTC, jonZlotnik approved these changes, later dismissed
I approve. Further changes can be made in a new branch. (like adding your stream operator)

2021-03-27 23:19 UTC, joshpham97 approved these changes

2021-03-27 23:23 UTC, merged